# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo:

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: /about/index.html

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left # sidebar's position (left or right)
social_links:
  github: https://github.com/dixudx
  linkedin: https://www.linkedin.com/pub/di-xu/71/991/7a1
  rss: https://dixu.me/atom.xml
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
